### ISSUE TITLE
META issue

### ISSUE THREAD

**Issue by Kakadu** [Kakadu/lablqml#70]
- [ ] Implement dynamic addition of signals/slots/qinvokable methods. It was [started here](https://github.com/mikhaylovilya/ocaml-syntax-extension/tree/main/caml_dynamic/stubs) but the approach is too clumsy and restrictive.
- [ ]  Implement 7 GUI tasks #68 
- [ ] in OCaml 5 demos are crashing on exit. Need to investigate
- [ ] Invenstigate which features are available from which version of Qt. (I think everything should work on Qt5 but...)
- [ ] Add demos with QML type compiler https://doc.qt.io/qt-6/qtqml-qml-type-compiler.html
- [ ] Add demos with QML script compiler https://doc-snapshots.qt.io/qt6-dev/qtqml-qml-script-compiler.html
- [ ]  Document and enhance PPX extensions
   - [ ]  Singleton's seems to be supported.
   - [ ] Old-style creation of objects should work (it allows QAbstractItemModels, '/dune_test' is about that)
   - [ ] What about Q_GADGET macro?
- [ ]  Technical debts
   - [ ]  Coverage, autoformatting, etc. 
   - [ ] Garbage collect issues.
